services:
  redis:
    image: redis:alpine
    container_name: redis-local
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
